config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :bookshops
  resources :publishers
  resources :books
  resources :authors
	root "books#index"
	post "/books/new", to: "books#new"
	post "/authors/new", to: "authors#new"
	post "/searches/new", to: "searches#new"	
end

app/models/bookshop.rb
class Bookshop < ApplicationRecord
	scope :find_book , ->(name) { where(id: Book.where("name = ?", name).pluck(:bookshop_id)).pluck(:name)}
	has_many :books, foreign_key: true
	has_many :publishers, foreign_key: true
end

app/controllers/bookshops_controller.rb
class BookshopsController < ApplicationController
  before_action :set_bookshop, only: %i[ show edit update destroy ]

  # GET /bookshops or /bookshops.json
  def index
    @bookshops = Bookshop.all
  end

  # GET /bookshops/1 or /bookshops/1.json
  def show
  end

  # GET /bookshops/new
  def new
    @bookshop = Bookshop.new
  end

  # GET /bookshops/1/edit
  def edit
  end

  # POST /bookshops or /bookshops.json
  def create
    @bookshop = Bookshop.new(bookshop_params)

    respond_to do |format|
      if @bookshop.save
        format.html { redirect_to @bookshop, notice: "Bookshop was successfully created." }
        format.json { render :show, status: :created, location: @bookshop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookshops/1 or /bookshops/1.json
  def update
    respond_to do |format|
      if @bookshop.update(bookshop_params)
        format.html { redirect_to @bookshop, notice: "Bookshop was successfully updated." }
        format.json { render :show, status: :ok, location: @bookshop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookshops/1 or /bookshops/1.json
  def destroy
    @bookshop.destroy
    respond_to do |format|
      format.html { redirect_to bookshops_url, notice: "Bookshop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookshop
      @bookshop = Bookshop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookshop_params
      params.require(:bookshop).permit(:book, :publisher, :name)
    end
end

app/helpers/bookshops_helper.rb
module BookshopsHelper
end

app/views/bookshops/_form.html.erb
<%= form_with(model: bookshop, local: true) do |form| %>
  <% if bookshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookshop.errors.count, "error") %> prohibited this bookshop from being saved:</h2>

      <ul>
      <% bookshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookshops/edit.html.erb
<h1>Editing Bookshop</h1>

<%= render 'form', bookshop: @bookshop %>

<%= link_to 'Show', @bookshop %> |
<%= link_to 'Back', bookshops_path %>

app/views/bookshops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookshops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookshops.each do |bookshop| %>
      <tr>
        <td><%= bookshop.name %></td>
        <td><%= link_to 'Show', bookshop %></td>
        <td><%= link_to 'Edit', edit_bookshop_path(bookshop) %></td>
        <td><%= link_to 'Destroy', bookshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookshop', new_bookshop_path %>
<%= link_to 'Books', new_polymorphic_path(Book) %>

app/views/bookshops/new.html.erb
<h1>New Bookshop</h1>

<%= render 'form', bookshop: @bookshop %>

<%= link_to 'Back', bookshops_path %>

app/views/bookshops/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @bookshop.name %>
</p>

<%= link_to 'Edit', edit_bookshop_path(@bookshop) %> |
<%= link_to 'Back', books_path %>