config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :bookshops
  resources :publishers
  resources :books
  resources :authors
	root "books#index"
	post "/books/new", to: "books#new"
	post "/authors/new", to: "authors#new"
	post "/searches/new", to: "searches#new"	
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: %i[ show edit update destroy ]

  # GET /searches or /searches.json
  def index
  	@publishers = Publisher.all
  	@bookshops = Bookshop.all
    @authors = Author.all
    @books = Book.all
    @searches = Search.all
  end

  # GET /searches/1 or /searches/1.json
  def show
  	@publishers = Publisher.all
  	@bookshops = Bookshop.all
    @authors = Author.all
    @books = Book.all
    @searches = Search.all
  end

  # GET /searches/new
  def new
  	@search = Search.new
  	@publishers = Publisher.all
  	@bookshops = Bookshop.all
    @authors = Author.all
    @book = Book.all
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches or /searches.json
  def create
    @search = Search.new(search_params)

    if @search.save
      redirect_to @search
    else
      render "new"
    end
  end


  # PATCH/PUT /searches/1 or /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: "Search was successfully updated." }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1 or /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: "Search was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:name)
    end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% @search.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <td>Name</td>


    </tr>
  </thead>

  <tbody>
    <% @searches.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of this book:</strong>
  <%= @search.name %>
</p>
<p>
  <strong>Author(s) of this book is:</strong>
  <% aid = Book.where(name: @search.name).pluck(:author_id) %>
  <% aid.each do |el| %>
  <%= Author.where(id: el).pluck(:name).to_s[2..-3] %>;
  <% end %>
</p>

<p>
  <strong>Book can be finded in:</strong>
  <% aid = Book.where(name: @search.name).pluck(:bookshop_id) %>
  <% aid.each do |el| %>
  <%= Bookshop.where(id: el).pluck(:name).to_s[2..-3] %>;
  <% end %>
</p>

<p>
  <strong>Publisher is:</strong>
  <% aid = Book.where(name: @search.name).pluck(:publisher_id) %>
  <%= Publisher.where(id: aid).pluck(:name).first %>;
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>